---
# Source: kubeapps/templates/apprepositories.yaml

apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  name: altemista
  annotations:
    "helm.sh/hook": post-install
  labels:
    chart: kubeapps-3.9.2
    release: kubeapps
    heritage: Tiller
    helm.sh/chart: kubeapps-3.9.2
    app.kubernetes.io/instance: kubeapps
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kubeapps
    app: kubeapps-internal-apprepository-controller
spec:
  type: helm
  url: https://core.harbor.altemista.cloud/chartrepo/library
  syncJobPodTemplate:
    spec:
      securityContext:
        runAsUser: 1001
---

apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  name: organization
  annotations:
    "helm.sh/hook": post-install
  labels:
    chart: kubeapps-3.9.2
    release: kubeapps
    heritage: Tiller
    helm.sh/chart: kubeapps-3.9.2
    app.kubernetes.io/instance: kubeapps
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: kubeapps
    app: kubeapps-internal-apprepository-controller
spec:
  type: helm
  url: http://harbor-harbor-core/chartrepo/library
  syncJobPodTemplate:
    spec:
      securityContext:
        runAsUser: 1001
---
