---
# Source: kubeapps/templates/apprepositories.yaml

apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  name: altemista
  annotations:
    "helm.sh/hook": pre-install
  labels:
    app: kubeapps-internal-apprepository-controller
    chart: kubeapps-3.4.3
    release: kubeapps
    heritage: Tiller
spec:
  type: helm
  url: https://core.testharbor.altemista.cloud/chartrepo/library
  syncJobPodTemplate:
    spec:
      securityContext:
        runAsUser: 1001
---

apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  name: organization
  annotations:
    "helm.sh/hook": pre-install
  labels:
    app: kubeapps-internal-apprepository-controller
    chart: kubeapps-3.4.3
    release: kubeapps
    heritage: Tiller
spec:
  type: helm
  url: http://harbor-harbor-core/chartrepo/library
  syncJobPodTemplate:
    spec:
      securityContext:
        runAsUser: 1001
---
