---
# Source: kubeapps/templates/tests/test-assetsvc.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "kubeapps-assetsvc-test"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: kubeapps-assetsvc-test
      image: docker.io/bitnami/nginx:1.19.2-debian-10-r32
      env:
        - name: ASSETSVC_HOST
          value: kubeapps-internal-assetsvc.altemistahub
        - name: ASSETSVC_PORT
          value: "8080"
      command:
        - bash
        - -c
        # We are requesting the "wordpress" chart to the chartsvc to check that everything works as expected
        # Also, we retry several times in case the repository is being populated at the time of executing this test
        - |
            n=0
            until [ "$n" -ge 5 ]; do
              if curl -o /tmp/output $ASSETSVC_HOST:$ASSETSVC_PORT/v1/clusters/default/namespaces/altemistahub/charts && cat /tmp/output && cat /tmp/output | grep wordpress; then
                break
              fi
              sleep 10
              ((n+=1))
            done
            if [ "$n" -eq 5 ]; then
              exit 1
            fi
  restartPolicy: Never

---
# Source: kubeapps/templates/tests/test-dashboard.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "kubeapps-dashboard-test"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: kubeapps-dashboard-test
      image: docker.io/bitnami/nginx:1.19.2-debian-10-r32
      env:
        - name: DASHBOARD_HOST
          value: kubeapps.altemistahub
      command:
        - sh
        - -c
        - curl -o /tmp/output $DASHBOARD_HOST && cat /tmp/output && cat /tmp/output | grep 'You need to enable JavaScript to run this app'
  restartPolicy: Never

