// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatedAsset) DeepCopyInto(out *OperatedAsset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatedAsset.
func (in *OperatedAsset) DeepCopy() *OperatedAsset {
	if in == nil {
		return nil
	}
	out := new(OperatedAsset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatedAsset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatedAssetList) DeepCopyInto(out *OperatedAssetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OperatedAsset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatedAssetList.
func (in *OperatedAssetList) DeepCopy() *OperatedAssetList {
	if in == nil {
		return nil
	}
	out := new(OperatedAssetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatedAssetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatedAssetSpec) DeepCopyInto(out *OperatedAssetSpec) {
	*out = *in
	in.Operator.DeepCopyInto(&out.Operator)
	in.Asset.DeepCopyInto(&out.Asset)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatedAssetSpec.
func (in *OperatedAssetSpec) DeepCopy() *OperatedAssetSpec {
	if in == nil {
		return nil
	}
	out := new(OperatedAssetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatedAssetStatus) DeepCopyInto(out *OperatedAssetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatedAssetStatus.
func (in *OperatedAssetStatus) DeepCopy() *OperatedAssetStatus {
	if in == nil {
		return nil
	}
	out := new(OperatedAssetStatus)
	in.DeepCopyInto(out)
	return out
}
