on:
  push:
    branches:
      - master
    paths-ignore:
      - 'deploy/**'
      - 'docs/**'
      - 'install.sh'
      - '*.md'
name: Build and push operator image
jobs:
    template:
      runs-on: ubuntu-latest

      steps:
        - name: Set up operator-sdk
          run: |
            RELEASE_VERSION=v0.14.1
            curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
            chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
            sudo mkdir -p /usr/local/bin/
            sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk
            rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu

        - name: Checkout code
          uses: actions/checkout@v1

        - name: Restore Cache
          uses: actions/cache@preview
          with:
            path: ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-

        - name: Build operator image
          run: operator-sdk build eu.gcr.io/coealtemista/aalm-operator --go-build-args "-o build/_output/bin/aalm-operator"

        - name: Push operator image to registry
          run: |
            echo ${{ secrets.DOCKER_REGISTRY_CREDENTIALS_BASE64 }} | base64 -d > keyfile.json
            cat keyfile.json | docker login -u _json_key --password-stdin https://eu.gcr.io
            docker push eu.gcr.io/coealtemista/aalm-operator
