on:
  push:
    paths-ignore:
      - '.github/**'
name: Process template and push
jobs:
    template:
      runs-on: ubuntu-latest

      steps:
        - name: Set up Helm
          run: curl -LO https://git.io/get_helm.sh && chmod 700 get_helm.sh && ./get_helm.sh

        - name: Checkout code
          uses: actions/checkout@v1

        - name: Helm init
          run: helm init --client-only

        - name: Add KubeApps repo
          run: helm repo add bitnami https://charts.bitnami.com/bitnami

        - name: Fetch and untar KubeApps Chart
          run: helm fetch bitnami/kubeapps --untar

        - name: Create temp directory (required in helm2)
          run: mkdir temp-process

        - name: Process template with Altemista values
          run: helm template --name kubeapps -f deploy/templates/kubeapps-values.yaml kubeapps/ --namespace altemistahub --output-dir temp-process

        - name: Move optional resources to their own file
          run: mv temp-process/kubeapps/templates/apprepositories.yaml deploy/manifests

        - name: Move tests to their own file && remove tests directory
          run: find temp-process/kubeapps/templates/tests -name '*.yaml' -exec cat {} \; -exec echo \; > deploy/manifests/kubeapps-tests.yaml && rm -r temp-process/kubeapps/templates/tests

        - name: Move cleanup resources to their own file && remove these files
          run: find temp-process/kubeapps/templates -name '*cleanup*.yaml' -exec cat {} \; -exec echo \; > deploy/manifests/kubeapps-cleanup.yaml && find temp-process/kubeapps/templates -name '*cleanup*.yaml' -exec rm -f {} \;

        - name: Save all processed YAMLs to one file
          run: find temp-process/ -name '*.yaml' -exec cat {} \; -exec echo \; > deploy/manifests/kubeapps.yaml

        - name: Commit files
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add deploy/manifests/
            git commit -m "[action] process template"

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
