on: push
name: Process template, push and release
jobs: 
    template:
      runs-on: ubuntu-latest
      container:
          image: alpine/helm:2.16.1
      steps:
        - name: Checkout code
          uses: actions/checkout@v1

        - name: Helm init
          run: helm init --client-only

        - name: Add KubeApps repo
          run: helm repo add bitnami https://charts.bitnami.com/bitnami

        - name: Fetch and untar KubeApps Chart
          run: helm fetch bitnami/kubeapps --untar

        - name: Create temp directory (required in helm2)
          run: mkdir temp-process

        - name: Process template with Altemista values
          run: helm template kubeapps -f deploy/templates/kubeapps-values.yaml kubeapps/ --namespace altemistahub --output-dir temp-process

        - name: Move optional resources to their own file
          run: mv temp-process/kubeapps/templates/apprepositories.yaml deploy/manifests

        - name: Move tests to their own file && remove tests directory
          run: find temp-process/kubeapps/templates/tests -name '*.yaml' -exec cat {} \; > deploy/manifests/kubeapps-tests.yaml && rm -r temp-process/kubeapps/templates/tests

        - name: Save all processed YAMLs to one file
          run: find temp-process/ -name '*.yaml' -exec cat {} \; > deploy/manifests/kubeapps.yaml

        - name: Add and Commit new processed files
          uses: EndBug/add-and-commit@v2
          with: 
            author_name: GitHub Action
            message: "[action] process template"
            path: "manifests"
            pattern: "*.yaml"
            force: false